docs: ✏️ link to community repo instead of webpage
seedcase-project/community pull request #71
Opened 2024-12-02 12:38 UTC by signekb

## Description

The other links in the table refer to the repos and not the repo websites, so this way it's aligned.
Alternatively, we should link to the websites instead. As long as it's aligned across tables and rows in the roadmap, I don't have any strong opinions on this :)

(This is a stacked PR on #70 to avoid merge conflicts)

## Reviewer Focus

This PR needs a quick review.

## Checklist

- [X] Rendered website locally

2024-12-02 12:42 UTC, K-Beicher submitted a review, later dismissed
Makes perfect sense

2024-12-02 13:03 UTC, martonvago requested changes

2024-12-02 13:03 UTC, martonvago commented on roadmap.qmd
> +| {{< var status.ongoing >}} | [`seedcase-project/community](https://community.seedcase-project.org/): Sharing knowledge and skills learned from attending conferences and workshops in research softwa
But wait, so is this supposed to link to the github repo now?

2024-12-03 08:37 UTC, signekb commented on roadmap.qmd
> +| {{< var status.ongoing >}} | [`seedcase-project/community](https://community.seedcase-project.org/): Sharing knowledge and skills learned from attending conferences and workshops in research softwa
```suggestion
| {{< var status.ongoing >}} | [`seedcase-project/community`](https://github.com/seedcase-project/community): Sharing knowledge and skills learned from attending conferences and workshops in research software and data engineering or operational management |
```

2024-12-03 08:38 UTC, signekb commented on roadmap.qmd
> +| {{< var status.ongoing >}} | [`seedcase-project/community](https://community.seedcase-project.org/): Sharing knowledge and skills learned from attending conferences and workshops in research softwa
Omg, I forgot to change the link itself, haha. Thanks!

2024-12-03 12:13 UTC, lwjohnst86 submitted a review, later dismissed

2024-12-03 12:15 UTC, merged